### ISSUE TITLE
Add properties panel component

### ISSUE THREAD

**Issue by oedemis** [bpmn-io/vue-bpmn#4]
__Describe the solution you'd like__

Offer an additional vue component which extends the current `vue-bpmn` with a [`bpmn-js-properties-panel`](https://github.com/bpmn-io/bpmn-js-properties-panel).

__Original Question__

is it possible to develop an app like the example
https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel
with vue-bpmn

**Comment by pinussilvestrus** [comment]
What about doing it exactly the way as described in the example [inside the vue component](https://github.com/bpmn-io/vue-bpmn/blob/master/src/index.vue#L26).  Did you already try to include the properties panel inside your `BpmnJS` instance?

**Comment by pinussilvestrus** [comment]
So to answer the question: Yes, it should be possible to create such a vue component. You'll have to update the existing component by adding another one with a properties panel attached.

We are open for external contribution ❤️

**Comment by sabatale** [comment]
Is the properties panel compatible with the original viewer (as opposed to the modeler)? I fail to see how the diagram would get updated with the properties values?

**Comment by nikku** [comment]
Nope, you cannot have a viewer with properties editing support.

**Comment by nikku** [comment]
Closing this as adding the properties panel is beyond this simple example.
