### ISSUE TITLE
Example in the readme doesn't match the example in the repo

### ISSUE THREAD

**Issue by Thundernator** [bpmn-io/vue-bpmn#5]
I wanted to use the example code in a vue.js cli project. So I copied the vue component which can be found in the readme of this repo. This leads me to a parsing error of the bpmn diagram file. The BPMN container is shown, but not the diagram.
In the example code lies a simple index.html and not a *.vue file, which would fit the readme. The example code itself works as expected, but I can't reproduce it with a *.vue component

__Steps to Reproduce__

1. create a new vue.js cli project
2. edit the package.json and install the dependencies for bpmn-io
3. replace the app.vue content with the example provided in the readme

__Expected Behavior__

The diagram should be loaded

__Environment__

- Host Firefox
- OS: windows 10
- Library version: 3.2.3

**Comment by nikku** [comment]
Please share a [codesandbox](https://codesandbox.io/) that reproduces your issue.

**Comment by Thundernator** [comment]
Here is the according sandbox : https://codesandbox.io/s/angry-villani-v2nhg

**Comment by nikku** [comment]
It looks like the diagram will be loaded once the `.bpmn` resource is not inlined but opened as an external URL.

See my fork of your sandbox where I use an external URL for the diagram:
https://codesandbox.io/s/happy-voice-vp7ov?file=/src/App.vue

Also note the error message that is being shown which indicates that what vue-bpmn receives as input to show is a HTML page, _not_ a BPMN document.

**Comment by Thundernator** [comment]
Great, that should fix the problem for me. But what if I want to use a local .bpmn resource?

**Comment by nikku** [comment]
> But what if I want to use a local .bpmn resource?

Then you'd fix your bundler setup and make sure that that local resource is available as a URL. This is something we cannot correct for you.

**Comment by Thundernator** [comment]
> 
> 
> > But what if I want to use a local .bpmn resource?
> 
> Then you'd fix your bundler setup and make sure that that local resource is available as a URL. This is something we cannot correct for you.

I solved the problem for me, but as far as I understand, the example you provide in the readme will never work out of the box without further changes to the bundler right? That is quite confusing for new users and I would suggest, that you exchange the local file in that example with the url you provided me as solution. So it would work out of the box and create less confusion for newcomers.
Maybe I'm wrong, but I wanted to suggest that so that you could improve the experience if I'm correct.
It was just overall confusing that there is a different example in the readme as in the sources.

**Comment by nikku** [comment]
Thanks for your feedback. That makes perfect sense and we'll point to a remote URL instead.

**Comment by nikku** [comment]
Updated the readme with a hint: https://github.com/bpmn-io/vue-bpmn/blob/master/README.md
