### ISSUE TITLE
Update to Vue 3

### ISSUE THREAD

**Issue by duansheli** [bpmn-io/vue-bpmn#7]
bpmn  current adaptation version is vue 2.6
recommended to upgrade to vue 3.x

**Comment by pinussilvestrus** [comment]
Thanks for reporting. Could you please [update the issue](https://github.com/bpmn-io/vue-bpmn/issues/new?assignees=&labels=enhancement&template=FEATURE_REQUEST.md) to fit our guidelines? Otherwise, it will hard to understand _why_ an upgrade would be needed.

**Comment by nikku** [comment]
As an alternative to https://github.com/bpmn-io/vue-bpmn/issues/7#issuecomment-772297730 you could also file a contribution (PR) to upgrade the example right away :muscle:.

**Comment by nikku** [comment]
Closing this issue as `pr-needed`. We welcome any contribution that updates this library to `vue@3`.
